name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:          
    - uses: actions/checkout@v3
    
    - name: Set up cache
      id: cache-cpm
      uses: actions/cache@v2.1.8
      with:
        path: ~/cpm-cache
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-
    
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 12
        platform: x64
    
    - name: xorg-dev
      run: sudo apt update && sudo apt install xorg-dev
    
    - name: Build CMake
      run: |
        mkdir build && cd build
        cmake -DCPM_SOURCE_CACHE=~/cpm-cache ..
        make -j2
